version: '3'
services:
  webapp:
    image: jeskz0rd/docker-bootcamp:go-whoami
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.frontend.rule=Host:jeskz0rd.example,www.jeskz0rd.example
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
