version: '3'
services:
  traefik:
    image: traefik:1.7.12-alpine
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./acme:/acme
    labels:
      - traefik.port=8080
    networks:
       - proxy

networks:
  proxy:
    external:
      name: proxy
